-- Destruction des tables
DROP TABLE RECIPEORDER;
DROP TABLE MENUORDER;
DROP TABLE INGREDIENTRECIPE;
DROP TABLE RECIPE;
DROP TABLE ORDERS;
DROP TABLE USERS;
DROP TABLE POSITIONS;
DROP TABLE ELEMENTMENU;
DROP TABLE INGREDIENT;
DROP TABLE TYPERECIPE;
DROP TABLE MENU;