-- Destruction des tables

DROP TABLE POSITION;
DROP TABLE ELEMENTMENU;
DROP TABLE INGREDIENTRECIPE;
DROP TABLE RECIPE;
DROP TABLE PURCHASE;
DROP TABLE USERS;
DROP TABLE ORDERS;
DROP TABLE MENU;
DROP TABLE INGREDIENT;
DROP TABLE ELEMENTORDER;